-- Create promotions table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.promotions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text,
    discount_percentage numeric,
    image_url text,
    link_url text,
    start_date timestamp with time zone,
    end_date timestamp with time zone,
    active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- Add columns if they don't exist (safety check)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'promotions' AND column_name = 'image_url') THEN
        ALTER TABLE public.promotions ADD COLUMN image_url text;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'promotions' AND column_name = 'link_url') THEN
        ALTER TABLE public.promotions ADD COLUMN link_url text;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'promotions' AND column_name = 'discount_percentage') THEN
        ALTER TABLE public.promotions ADD COLUMN discount_percentage numeric;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'promotions' AND column_name = 'start_date') THEN
        ALTER TABLE public.promotions ADD COLUMN start_date timestamp with time zone;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'promotions' AND column_name = 'end_date') THEN
        ALTER TABLE public.promotions ADD COLUMN end_date timestamp with time zone;
    END IF;
END $$;

-- Enable RLS
ALTER TABLE public.promotions ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts
DO $$
DECLARE pol RECORD;
BEGIN
  FOR pol IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='promotions' LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.promotions', pol.policyname);
  END LOOP;
END $$;

-- Create Policies
CREATE POLICY "Enable read access for all users" ON "public"."promotions"
FOR SELECT TO public USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON "public"."promotions"
FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users only" ON "public"."promotions"
FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Enable delete for authenticated users only" ON "public"."promotions"
FOR DELETE TO authenticated USING (true);

-- Grants
GRANT SELECT ON TABLE public.promotions TO anon;
GRANT ALL PRIVILEGES ON TABLE public.promotions TO authenticated;
GRANT ALL PRIVILEGES ON TABLE public.promotions TO service_role;
